name: APT repository cleanup

on:
  schedule:
    - cron:  '* 4/4 * * *'

jobs:
  repo-maintenance:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Delete old versions
      env:
        BINTRAY_USERNAME: xploitednoob
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        BINTRAY_GPG_PASSPHRASE: ${{ secrets.BINTRAY_GPG_PASSPHRASE }}
      run: |
        ./scripts/package_uploader.sh -c $(cd ./packages; echo *)
